spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://database-1.ccbd1uk8wp0e.ap-northeast-2.rds.amazonaws.com:3306/weekand-prod
        username: admin
        password: ${/weekand/mysql/password}

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    redis:
        host: 127.0.0.1
        port: 6379

jwt:
    secret: ${/weekand/jwt/secret}
    access-token-expiry: 1800000
    refresh-token-expiry: 2592000000
    access-token-header: Access-Token
    refresh-token-header: Refresh-Token

awsParameterStorePropertySource:
    enabled: true
